### ISSUE TITLE
[FavIcon] There is not fav icon in website

### ISSUE THREAD

**Issue by malejaps** [alvaromartinez986/banquetesAntonyPage#12]
**Actual:** There is not fav icon in website

**Expected:** There is a fav icon in website. Favicon suggestion:
```
<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
<link rel="icon" href="/favicon.ico" type="image/x-icon">
```

![favicon](https://user-images.githubusercontent.com/9902912/36035404-be864b6c-0d84-11e8-89d1-ce1b61b8cd01.png)

**Evidence:**
![image](https://user-images.githubusercontent.com/9902912/36034325-baf367f8-0d81-11e8-87a9-508ae30404d0.png)

**Comment by malejaps** [comment]
Verified.

**Comment by malejaps** [comment]
**Actual:** There is not fav icon in website

**Expected:** There is a fav icon in website

**Evidence:**
![image](https://user-images.githubusercontent.com/9902912/38510458-cf996684-3bea-11e8-9999-9a8cb293373a.png)

**Comment by alvaromartinez986** [comment]
Resolved again

**Comment by malejaps** [comment]
Verified and fixed.
