### ISSUE TITLE
[Services] Text of "Alquileres" should be changed

### ISSUE THREAD

**Issue by malejaps** [alvaromartinez986/banquetesAntonyPage#19]
**Actual:** Title and content of "Alquileres" service is outdated

**Expected:** Title and content of "Alquileres" should be:

Title: Salones de Eventos
Content: Recomendación de salones, decoración, música, alquiler de sillas, mesas o mantelería.

**Evidence:**
![image](https://user-images.githubusercontent.com/9902912/39638974-8857e0fa-4f8d-11e8-94d3-bd5573a33fd2.png)
)

**Comment by alvaromartinez986** [comment]
Text changed.

**Comment by malejaps** [comment]
Verified and fixed.
