### ISSUE TITLE
[Menus] Order of menus is not user-friendly 

### ISSUE THREAD

**Issue by malejaps** [alvaromartinez986/banquetesAntonyPage#2]
**Actual:** Order of menus is not user-friendly  (Check Evidence)

**Expected:** Colors of menus pictures should be according to a better visual order, more user-friendly. Set pictures with yellow background on each corner. 

**Evidence:**
Url: https://alvaromartinez986.github.io/banquetesAntonyPage/#portfolio

![image](https://user-images.githubusercontent.com/9902912/35742675-29e718e0-0809-11e8-8dc9-cd25311459e7.png)

**Comment by alvaromartinez986** [comment]
Images reordered.

**Comment by malejaps** [comment]
Verified and resolved correctly.

![image](https://user-images.githubusercontent.com/9902912/35866078-37d66a46-0b24-11e8-8e24-92e0ca5dffbf.png)
