### ISSUE TITLE
[Contact] Responsive design is incorrect in Contact section

### ISSUE THREAD

**Issue by malejaps** [alvaromartinez986/banquetesAntonyPage#23]
**Actual:**
Responsive design is incorrect in Contact section. Check Evidence of issue found using app in Phone Samsumg Galaxy J5

**Expected:**
Responsive design is correct in Contact section

**Evidence:**
![screenshot_20180504-145729](https://user-images.githubusercontent.com/9902912/39652848-99de26a0-4fb4-11e8-8ee0-a608f741b8f9.png)

**Comment by alvaromartinez986** [comment]
This issue is partially resolved because the menu and the modals components it could be improved

**Comment by malejaps** [comment]
Verified Contact section fixed. As you mentioned, menu and the modals components it could be improved

**Comment by alvaromartinez986** [comment]
You can see the new features for the responsive site :)

**Comment by alvaromartinez986** [comment]
Menu issue resolved 🥇

**Comment by alvaromartinez986** [comment]
Verified.

**Comment by malejaps** [comment]
Verified and fixed.
