### ISSUE TITLE
[Welcome] Logo of navbar doesn't go to Welcome Section

### ISSUE THREAD

**Issue by malejaps** [alvaromartinez986/banquetesAntonyPage#4]
**Actual:** Logo of navbar doesn't go to Welcome Section. Check how url changes between evidences when do click in Logo but section continues as the same section.

**Expected:**  Logo of navbar should go to Welcome Section

**Evidence:**
Before click on Logo:
![image](https://user-images.githubusercontent.com/9902912/35743386-7a08d316-080b-11e8-87a2-c9158c215d9f.png)

After click on Logo:
![image](https://user-images.githubusercontent.com/9902912/35743410-89c23824-080b-11e8-9f1d-401bb6c59868.png)

**Comment by alvaromartinez986** [comment]
Resolved.

**Comment by malejaps** [comment]
Verified.
