### ISSUE TITLE
[Welcome] Background image and letters of main title don't have a good contrast

### ISSUE THREAD

**Issue by malejaps** [alvaromartinez986/banquetesAntonyPage#9]
**Actual:** Background image and letters of main title don't have a good contrast in colors (Check Evidence)

**Expected:** Background image and letters of main title should have a good contrast in colors

**Evidence**
![image](https://user-images.githubusercontent.com/9902912/35983075-470ed3d0-0cbf-11e8-9895-97066f24484c.png)

**Comment by alvaromartinez986** [comment]
again? :(

**Comment by malejaps** [comment]
Verified.
![image](https://user-images.githubusercontent.com/9902912/35985785-6758fa84-0cc5-11e8-907f-d77e1f454890.png)
